name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: |
        git submodule init
        git submodule update
    - name: cmake
      run: mkdir _build && cd _build && cmake ../ -DENABLE_CXX17=OFF
    - name: build
      run: cd _build && cmake --build ./ -- VERBOSE=1
