name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        compiler: [g++, clang, g++-4.8]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: |
        git submodule init
        git submodule update
    - if: matrix.compiler == 'g++-4.8'
      name: install gcc 4.8
      run: |
        sudo apt-get install g++-4.8
        dpkg --list | grep compiler
        echo ::set-env name=CC::gcc-4.8
        echo ::set-env name=CXX::g++-4.8
    - name: Set env clang
      if: matrix.compiler == 'clang'
      run: |
        echo ::set-env name=CC::clang
        echo ::set-env name=CXX::clang
    - name: cmake
      run: mkdir _build && cd _build && cmake ../ -DENABLE_CXX17=OFF
    - name: build
      run: cd _build && cmake --build ./
