name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        compiler: [g++, g++-4.8]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: |
        git submodule init
        git submodule update
    - if: matrix.compiler == 'g++-4.8' && matrix.os != 'macOS-latest'
      name: install gcc 4.8
      run: |
        sudo apt-get install g++-4.8
        dpkg --list | grep compiler
        echo "CC=gcc-4.8" >> $GITHUB_ENV
        echo "CXX=g++-4.8" >> $GITHUB_ENV
    - name: Set env clang
      if: matrix.compiler == 'clang'
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang" >> $GITHUB_ENV
    - name: cmake
      run: mkdir _build && cd _build && cmake ../ -DENABLE_CXX17=OFF
    - name: build
      run: cd _build && cmake --build ./