name: MacOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: |
        git submodule init
        git submodule update
    - name: install OpenSSL
      run: brew install openssl
    - name: cmake
      run: |
        mkdir _build
        cd _build
        export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
        export OPENSSL_LIB_DIR=$(brew --prefix openssl)"/lib"
        export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)"/include"
        cmake ../ -DENABLE_CXX17=OFF
    - name: build
      run: cd _build && cmake --build ./
