name: Ubuntu-20.04
on: [push]

jobs:
  build:
    strategy:
      matrix:
        compiler: [g++]
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: |
        git submodule init
        git submodule update
        dpkg --list | grep compiler
    - if: matrix.compiler == 'g++-4.8' && matrix.os != 'macOS-latest'
      name: install gcc 4.8
      run: |
        # It has become quite tricky to install GCC 4.8 on Ubuntu 20.04.
        # This way does no longer work :(
        sudo apt-get install g++-4.8
        dpkg --list | grep compiler
        echo "CC=gcc-4.8" >> $GITHUB_ENV
        echo "CXX=g++-4.8" >> $GITHUB_ENV
    - name: Set env clang
      if: matrix.compiler == 'clang'
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang" >> $GITHUB_ENV
    - name: cmake
      run: mkdir _build && cd _build && cmake ../ -DENABLE_CXX17=OFF
    - name: build
      run: cd _build && cmake --build ./
